export const templates = {
    season: {
        "Name": "name",
        "Id": "userId",
        "Matches Played": "matchesPlayed",
        "Rounds Played": "roundsPlayed",
        "Minutes Played": "minutesPlayed",
        "Wins": "matchesWon",
        "Loses": "matchesLost",
        "K/D": "killDeathRatio",
        "Kills": "kills",
        "Headshots": "headshots",
        "Headshot Accuracy": "headshotAccuracy",
        "Melee Kills": "meleeKills",
        "Team Kills": "teamKills",
        "Kills /round": "killsPerRound",
        "Rounds w/ Kill": "roundsWithAKill",
        "Rounds w/ Multi-kill": "roundsWithMultiKill",
        "Opening Kills": "openingKills",
        "Rounds w/ Opening Kill": "roundsWithOpeningKill",
        "Assists": "assists",
        "Deaths": "death",
        "Opening Deaths": "openingDeaths",
        "Rounds w/ Opening Death": "roundsWithOpeningDeath",
        "KOST": "roundsWithKOST",
        "Rounds Survived": "roundsSurvived",
        "Revives": "revives",
        "Time Alive /match": "timeAlivePerMatch",
        "Time Dead /match": "timeDeadPerMatch",
        "Distance Traveled": "distanceTravelled",
        "Distance /round": "distancePerRound"
    },
    weekly: {
        "Name": "name",
        "Id": "userId",
        "Matches Played": "matchesPlayed",
        "Rounds Played": "roundsPlayed",
        "Wins": "matchesWon",
        "Loses": "matchesLost",
        "K/D": "killDeathRatio",
        "Kills": "kills",
        "Assists": "assists",
        "Deaths": "death",
        "KOST": "roundsWithKOST"
    }
};